### ISSUE TITLE
HeartRateSensor missing constructor

### ISSUE THREAD

**Issue by JeremyJeanson** [SergioMorchon/fitbit-sdk-types#134]
When  i try to use the 4.3.3 i cannot build. I have an error :
No constituent of type 'void | HeartRateSensorConstructor'

It happen on a call to the contructor of the HeartRateSensor.
hrm = new HeartRateSensor();

I cannot use the last version of fitbit-sdk-types.
When i use the old version 4.0.0. It build without problems.

**Comment by SergioMorchon** [comment]
Hi :)

# Explanation
Since #91 (shipped in the [v4.0.1 fix](https://github.com/SergioMorchon/fitbit-sdk-types/releases/tag/v4.0.1)), sensors may or may not be present because of the different Fitbit devices hardware.
That happened for first time when introduced the Versa Lite, that lacks for some sensors (like the barometer).
So I asked Fitbit engineering members, and to write future-proof code for the Fitbit SDK, all the _sensors_ should be checked before used, as the SDK can return {{void}} for any of them at some point in the present/future, just like happened with Versa Lite, when *a lot* of apps stopped working because they didn't check for Barometer presence and had to be blacklisted.

# Solution
Check for the sensor presence before using it, as in the 
[heart-rate/peeking-current-heart-rate test](https://github.com/SergioMorchon/fitbit-sdk-types/blob/master/test-code-samples/app/heart-rate/peeking-current-heart-rate.ts)

**Comment by JeremyJeanson** [comment]
Thank you,

I undertand. My test was a little older ;)

I had this:
```
import { me } from "appbit";
import { HeartRateSensor } from "heart-rate";

let hrm: HeartRateSensor;

export function initialize(...): void {
  if (me.permissions.granted("access_heart_rate")
    && me.permissions.granted("access_user_profile")) {
    hrm = new HeartRateSensor();

```

As you said, it should be:
```
import { me } from "appbit";
import { HeartRateSensor } from "heart-rate";

let hrm: HeartRateSensor;

export function initialize(...): void {
  if (HeartRateSensor
    && me.permissions.granted("access_heart_rate")
    && me.permissions.granted("access_user_profile")) {
    hrm = new HeartRateSensor();
```

Thank you again ;)

**Comment by SergioMorchon** [comment]
Yep, that's it!
