### ISSUE TITLE
The <animate> element is missing in the device types

### ISSUE THREAD

**Issue by gregoiresage** [SergioMorchon/fitbit-sdk-types#145]

**Comment by SergioMorchon** [comment]
Hi @gregoiresage!
Do you have more details? That element doesn't exist in the [document API](https://dev.fitbit.com/build/reference/device-api/document/)

**Comment by bingtimren** [comment]
Maybe @gregoiresage is referring to [https://dev.fitbit.com/build/guides/user-interface/animations/](https://dev.fitbit.com/build/guides/user-interface/animations/) ?

**Comment by SergioMorchon** [comment]
Yes @bingtimren , I also think so. But what I need is the JS API spec 🙁
Because not every SVG element or attribute has a JS binging. Furthermore, even when we find some element that can be used somehow from JS, we don't fully know the expected types and attributes, or even if it is expected that we can use it and Fotbit will maintain that APIs.

Those are the reasons why this project tries to add only officially documented APIs in the proper API section at dev.fitbit.com
