### ISSUE TITLE
onChange for TSX doesn't match actual types returned

### ISSUE THREAD

**Issue by GaiusCoffey** [SergioMorchon/fitbit-sdk-types#160]
Hi,
`    <TextInput type="number" title="Enter whole seconds" 
        value={props.settings[secsKey]} 
        onChange={
          value=>{
            console.log(value+" is "+(typeof value)+" "+value);
          }
        } 
        />`
Gets console.log of:
`Settings: [object Object] is object [object Object]`
And in reality, the type of value is {name:string};
TypeScript defs say that value should be a simple string.

Given the state of the Fitbit settings components, I daresay yours is what _should_ be correct, but it isn't _actually_ correct. :(

G

**Comment by SergioMorchon** [comment]
Indeed you found a bug present since SDK1.
Fitbit dev site says (from [`TextInput`](https://dev.fitbit.com/build/reference/settings-api/#textinput)):
> `onChange`: a function that is called every time the text value is saved by the user. Takes the new value of the text as an argument.

So it must be the *text*, and not an object with a `name` property that holds the `value` (nothing to wo with a "name").
Here you have a report I did long time ago, and already confirmed by @orviwan that they have it on their bug tracker: https://community.fitbit.com/t5/SDK-Development/Some-bugs-in-documentation-and-SDK/m-p/3208513/highlight/true#M7583

They added a new *undocumented* API that turns `TextInput` to work as you would expect, with `useSImpleValue` (see #138).
